# GET http://localhost:3000/getgoing HTTP/1.1

# GET http://localhost:3000/ping HTTP/1.1

POST http://localhost:3000/ HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Content-Type: application/json

{
  "name": "Test2",
  "todo": "Test Todo API"
}