# GET http://localhost:3000/getgoing HTTP/1.1

# GET http://localhost:3000/ping HTTP/1.1

POST http://localhost:3000/  HTTP/1.1
content-type: application/json

{
    "name": "Test",
    "todo": "Test Todo API"
}